### ISSUE TITLE
请不要在技术开发者的平台上讨论政治

### ISSUE THREAD

**Issue by liu-yabin** [zmike1993/hello-world#21]

**Comment by weijiang89f** [comment]
你是不是搞错了，群发的？我从来不参与这些事




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liu yabin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 中午11:04
收件人:&nbsp;"zmike1993/hello-world"<hello-world@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zmike1993/hello-world] 请不要在技术开发者的平台上讨论政治 (#21)





 
你喜欢搞政治是你的事情，但是能不能建立一个你们自己的平台。这个世界上有人喜欢同性恋，这没有问题，但是你到男女交友的平台上发表同性恋的主张是不是不太合适。
 收多少钱才能干出这么恶心人的事情。

**Comment by fcl1892** [comment]
咋回事哦？？

**Comment by zmike1993** [comment]
哈哈，你能用什么样的技术平台本身就是个政治问题。@liu-yabin

**Comment by LuoTianHua** [comment]
您上github需要翻墙按难道不是一个政治问题而是技术问题？
